deployments:
    gothamist:
      port_forwarding:
          80:3000
      environment:
          - NUXT_HOST=0.0.0.0
          - NUXT_PORT=3000
          - API=https://cms.demo.nypr.digital/api/v2/
          - GTM_ID=GTM-M2S32K5
          - IMAGE_BASE_URL=https://cms.demo.nypr.digital/images/
          - MAILCHIMP_API=https://api.demo.nypr.digital/opt-in/v1/subscribe/mailchimp
          - NEWSLETTER_API=https://api.demo.nypr.digital/email-proxy/subscribe
          - DISQUS_API=https://disqus.com/api/3.0
          - DISQUS_PUBLIC_KEY=e6CVgEaLZqw0RNacE0YTx0PwnjyXh8X8QogknYzUX34hJ4k7EmUVPxVCD5FjHjqp
          - SENTRY_DSN=https://525e09964a6d4c87bfa58617dc758455@o557978.ingest.sentry.io/5743108
          - SENTRY_ENVIRONMENT=demo
          - WHATS_ON_API=https://api.demo.nypr.digital/api/v4/whats_on/
          - ENV=demo
      run_options:
          --env NUXT_HOST=$NUXT_HOST
          --env NUXT_PORT=$NUXT_PORT
          --env API=$API
          --env GTM_ID=$GTM_ID
          --env IMAGE_BASE_URL=$IMAGE_BASE_URL
          --env MAILCHIMP_API=$MAILCHIMP_API
          --env NEWSLETTER_API=$NEWSLETTER_API
          --env DISQUS_API=$DISQUS_API
          --env DISQUS_PUBLIC_KEY=$DISQUS_PUBLIC_KEY
          --env SENTRY_DSN=$SENTRY_DSN
          --env SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT
          --env WHATS_ON_API=$WHATS_ON_API
          --env ENV=$ENV
