---
templates:
  defaults: &defaults
    docker:
      - image: cimg/node:14.18
        environment:
          JOBS: 2

  node_key: &node_key
    key: node-deps-{{ checksum "circle.yml" }}-{{ checksum "package-lock.json" }}

  restore_node: &restore_node
    restore_cache:
      <<: *node_key

  deploy_static: &deploy_static
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node
      - deploy:
          name: Deploy to S3
          command: |
            env | sed -n "s/^${ENV}_//p" >> .env
            set -o allexport && source .env && set +o allexport
            npm install
            npm run deploy

  deploy_nuxt: &deploy_nuxt
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          key: deploy-{{ checksum "circle.yml" }}
      - run:
          name: Install Requirements
          command: |
            if [[ ! -d ~/.venv ]]; then
              python3 -m venv ~/.venv
              source ~/.venv/bin/activate
              pip3 install -U git+https://github.com/nypublicradio/nyprsetuptools.git
            fi
      - deploy:
          name: Deploy Nuxt
          command: |
            TAG=${TAG:-$CIRCLE_TAG}
            source ~/.venv/bin/activate
            nyprsetuptools DockerDeploy \
              --fargate \
              --cpu=1024 \
              --memory-reservation=2048 \
              --ecr-repository=gothamist-vue \
              --ecs-cluster=fastboot \
              --execution-role=gothamist-vue-$ENV \
              --task-role=gothamist-vue-$ENV \
              --ports=80 \
              --environment=$ENV \
              --tag=$TAG \
              --wait=300 \
              --enable-execute-command \
      - save_cache:
          key: deploy-{{ checksum "circle.yml" }}
          paths:
            - ~/.venv

  filter_demo: &filter_demo
    filters:
      branches:
        only: main
      tags:
        only: demo

  filter_prod: &filter_prod
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v[0-9]+\.[0-9]+\.[0-9]+/


version: 2
jobs:
  build-static:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node
      - run:
          name: Install node dependencies
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          <<: *node_key
          paths:
            - node_modules

  test-static:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node
      - run:
          name: Install JUnit coverage reporter
          command: npm install --save-dev jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: node ./node_modules/jest/bin/jest.js --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit


  deploy-static-demo:
    environment:
      ENV: DEMO
    <<: *deploy_static

  deploy-nuxt-demo:
    environment:
      ENV: demo
      TAG: demo
    <<: *deploy_nuxt

  deploy-static-prod:
    environment:
      ENV: PROD
    <<: *deploy_static

  deploy-nuxt-prod:
    environment:
      ENV: prod
    <<: *deploy_nuxt


workflows:
  version: 2
  just-test:
    jobs:
      - build-static:
          filters:
            branches:
              ignore: main
      - test-static:
          requires:
            - build-static

  deploy-demo:
    jobs:
      - build-static:
          <<: *filter_demo
      - test-static:
          <<: *filter_demo
          requires:
            - build-static
      - deploy-static-demo:
          <<: *filter_demo
          requires:
            - build-static
      - deploy-nuxt-demo:
          <<: *filter_demo
          requires:
            - build-static

  deploy-prod:
    jobs:
      - build-static:
          <<: *filter_prod
      - test-static:
          <<: *filter_prod
          requires:
            - build-static
      - deploy-static-prod:
          <<: *filter_prod
          requires:
            - build-static
      - deploy-nuxt-prod:
          <<: *filter_prod
          requires:
            - build-static

